apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: study-k8s-rails-web-deployment
spec:
  template:
    metadata:
      labels:
        app: study-k8s-rails-web
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image: study/web:1.8
          name: web
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-server
              containerPort: 80
          volumeMounts:
            - mountPath: /usr/local/src/study_k8s_rails/public
              name: web-assets
              readOnly: true
            - mountPath: /usr/local/src/study_k8s_rails/tmp/sockets
              name: web-sock
          livenessProbe: # healthcheck
            httpGet:
              path: /status # /status で確認
              port: 80
            initialDelaySeconds: 5 # 5s後にチェックする
            timeoutSeconds: 3 # 3s 以上は timeout
            failureThreshold: 10 # 失敗回数
        - image: study/app:1.8
          name: app
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "cp -rf /tmp/public/* /usr/local/src/study_k8s_rails/public; bundle exec puma -C config/puma/production.rb"]
#          args: ["-c", "cp -rf /tmp/public/* /usr/local/src/study_k8s_rails/public; bundle exec rake assets:precompile RAILS_ENV=production; bundle exec puma -C config/puma/production.rb"]
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "bundle exec pumactl -P tmp/pids/puma.pid halt && sleep 60"]
          env:
            - name: RAILS_ENV
              value: production
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: rails
                  key: secret-key
          volumeMounts:
            - mountPath: /usr/local/src/study_k8s_rails/public
              name: web-assets
            - mountPath: /usr/local/src/study_k8s_rails/tmp/sockets
              name: web-sock
      volumes:
        - name: web-assets
          emptyDir: {}
        - name: web-sock
          emptyDir: {}