# Usage:
#   echo -n "key-value" | base 64
#   kubectl create -f kubernetes/secrets/rails.yaml
apiVersion: v1
kind: Secret
metadata:
  name: rails
type: Opaque
data:
  secret-key: ZTZlMjc1M2M0MWVkYjE0MWZiMjRlZWVkMWQ1ZWYwMjNkNTY5YTgwNTg0NDE5MDVmNjI4OWEwNTY3NGM3YjgwMGUxYTU5MDdlODVkN2RlM2Y5YjNiOTkzYWZmMWIyOTA1MGU0NzU4MWVmYzNmOGUwMDc0MzRjN2Y2YTU4NTc4YTc=
