defaults: &defaults
  fog_provider: 'Google'
  google_storage_access_key_id: "<%= ENV['GOOGLE_STORAGE_ACCESS_KEY_ID'] %>"
  google_storage_secret_access_key: "<%= ENV['GOOGLE_STORAGE_SECRET_ACCESS_KEY'] %>"
  fog_directory: "study-k8s"
  # You may need to specify what region your storage bucket is in
  # fog_region: "eu-west-1"
  existing_remote_files: keep
  # To delete existing remote files.
  # existing_remote_files: delete
  # Automatically replace files with their equivalent gzip compressed version
  # gzip_compression: true
  # Fail silently.  Useful for environments such as Heroku
  # fail_silently: true
  # Allow custom assets to be cacheable. Note: The base filename will be matched
  # cache_asset_regexps: ['cache_me.js', !ruby/regexp '/cache_some\.\d{8}\.css/']

development:
  <<: *defaults
  enabled: false

test:
  <<: *defaults
  enabled: false

staging:
  <<: *defaults

production:
  <<: *defaults
